# Generated by Django 2.2.14 on 2020-12-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('publication_date', models.DateTimeField()),
                ('text_publication', models.CharField(max_length=200)),
                ('tag', models.ManyToManyField(related_name='publicacion', to='tags.Tag')),
            ],
        ),
    ]
